---
- hosts: test_hosts_group
  tasks:
    - name: install epel-release
      dnf : name=epel-release state=latest
    - name: install nginx web server
      dnf: name=nginx state=present
    - name : Start nginx web server
      service: name=nginx state=started