---
- name: localhost에서
  hosts: localhost
  gather_facts: no
  tasks:
    - name: command1111111
      shell: whoami
      register: whoami1
      
    - name: localhost에서 정보 수집
      debug:
        msg: "{{ whoami1 }}"

    ##### State Httpd #####
    - name: command2222222
      shell: ip a
      register: whoami2
      delegate_to: deployed_vm

    - name: 배포 가상머신 ip 정보 수집
      debug:
        msg: "{{ whoami2 }}"
      delegate_to: deployed_vm
