---
- name: localhost에서
  hosts: localhost
  gather_facts: no
  tasks:
    - name: command1111111
      shell: whoami
      register: whoami1
      
    - name: localhost에서 정보 수집
      debug:
        msg: "{{ whoami1 }}"
##### State Httpd #####
- name: "State Httpd"
  hosts: deployed_vm
  gather_facts: no
  vars:
    - service: sshd.service
  tasks:

    - name: command2222222
      shell: ip a
      register: whoami2

    - name: 배포 가상머신 ip 정보 수집
      debug:
        msg: "{{ whoami2 }}"
