---
- name: Genie를 활용한 Mold VM 배포
  hosts: localhost
  gather_facts: no
  vars:
    file_contents: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDWSq5GAdyDDFjiDlzgUYFVOf5+7dF0Q3CVxEhKKrm6MyXJ4FwG7Ah2/9CoL+Q/VHcllwcomb9mPIuvaFt9l3E3rz0hLZWJmP1ynAB2ai4R0ba4QSz/HjJQfYe8scBIiJ86yeLRBvLdkYfc946NbHk6ZrK0PZxc+BArszCYN/cmmyWzogEh325h6jhmEqZv5w8CSHZ9olMFkPEkq3joXQGSf2GVhdDYkxY1P/1kZCKXbuLAdpztKCxDB8q9tDBw3EzSlenrf4+1GMdTFRh2p/QC3vETXRkErDLXGzkW8AnHZLK4arc0swGHuR1lO4tAoqjQDHaQZW/7bAImKTfT0iaEXiGpfweLjBdLCCeZyb51IKeMRoSdJ54FHSJtTr9PEBnrJQdWanrnl+9REoerDAYI0xAJGyi388b5oAoxb3i3UrCdgi/cWEbfGlxqamwu0IjkKLo+5s9h4j5qVLxBzkmnOZ2olWTa2kOlGo2c37kj6jLyRXHUY44NuIqtmk+nyDbpqOQHUPNAEdjMsQyOxfZqLrR7JYpPOMeNnmgNdJDtAPb7qsYXTDSsdP3vtKZq37DilZnTZA7vqEhuqfCnLKwGTZxWymp88ehWFiSY6Glee3XXywUaEI3EPElx47NtiS+PRXFIvkYzkiyAceBKyWGswfAECOrb0HwLoZDL5dbTGw=='
  tasks:
##### Deploy VirtualMachine #####

    - name: 가상머신 생성
      cs_instance:
        api_url: "{{ MOLD_API_URL }}"
        api_key: "{{ MOLD_API_KEY }}"
        api_secret: "{{ MOLD_SECRET_KEY }}"
        zone: Zone
        name: hwryu-deploy-vm2
        template: AutomationController-0525
        service_offering: 2C-4GB-RBD
        ssh_key: AutomationController-hwryu
        networks:
          - genie-network1
        user_data: |
            #cloud-config
            disable_root: false
            ssh-authorized-keys:
              - {{ file_contents }}
      delegate_to: localhost

    - name: 배포한 가상머신 정보 수집
      cs_instance_info:
        api_url: "{{ MOLD_API_URL }}"
        api_key: "{{ MOLD_API_KEY }}"
        api_secret: "{{ MOLD_SECRET_KEY }}"
        name: hwryu-deploy-vm2
      delegate_to: localhost
      register: vm

    - name: 배포 가상머신 ip 정보 수집
      debug:
        msg: "{{ vm.instances[0].nic[0].ipaddress }}"

    - name: Create Public IP
      cs_ip_address:
        api_url: "{{ MOLD_API_URL }}"
        api_key: "{{ MOLD_API_KEY }}"
        api_secret: "{{ MOLD_SECRET_KEY }}"
        zone: Zone
        network: genie-network1
      register: ac_public_ip

    - name: Public IP 정보 수집
      debug:
        msg: "{{ ac_public_ip.ip_address }}"

    - name: Create a static NAT for 'ac_public_ip.ip_address' to hwryu-deploy-vm2
      cs_staticnat:
        api_url: "{{ MOLD_API_URL }}"
        api_key: "{{ MOLD_API_KEY }}"
        api_secret: "{{ MOLD_SECRET_KEY }}"
        ip_address: "{{ ac_public_ip.ip_address }}"
        zone: Zone
        vm: hwryu-deploy-vm2
      delegate_to: localhost

    - name: 배포 가상머신 인메모리 inventory에 등록
      add_host:
        hostname: "{{ vm.instances[0].nic[0].ipaddress }}"
        groups:
          - deployVmIp

    - name: Allow 88 port for public ip
      cs_firewall:
        api_url: "{{ MOLD_API_URL }}"
        api_key: "{{ MOLD_API_KEY }}"
        api_secret: "{{ MOLD_SECRET_KEY }}"
        ip_address: "{{ ac_public_ip.ip_address }}"
        zone: Zone
        start_port: 80
        end_port: 80
        protocol: tcp
      delegate_to: localhost

    - name: Allow 22 port for public ip
      cs_firewall:
        api_url: "{{ MOLD_API_URL }}"
        api_key: "{{ MOLD_API_KEY }}"
        api_secret: "{{ MOLD_SECRET_KEY }}"
        ip_address: "{{ ac_public_ip.ip_address }}"
        zone: Zone
        start_port: 22
        end_port: 22
        protocol: tcp
      delegate_to: localhost
