---
- name: CS
  hosts: localhost
  tasks:
    - name: Gather instance information
      cs_instance_info:
        api_url: "{{ api_url }}"
        api_key: "{{ api_key }}"
        api_secret: "{{ api_secret }}"
        name: CentOS-8-5-2111-hwryu-07
      delegate_to: localhost
      register: vm

    - name: Show the returned results of the registered variable
      debug:
        msg: "{{ vm }}"
