---
- name: AWX 템플릿 배포
  hosts: genie_vm
  vars:
    base_path: 'genie'
    genie_ip: 'localhost'
  gather_facts: no
  tasks:

  - name: AWX 초기 관리자 패스워드 추출
    shell: kubectl get -n awx secret awx-admin-password -o jsonpath="{.data.password}" | base64 --decode
    register: admin_password

  # Wordpress
  - name: Create wordpress deploy playbook
    awx.awx.job_template:
      name: '['AC가상머신']' 정보 수집
      description: 오토메이션 컨트롤러 정보를 읽어오는 템플릿 입니다.
      job_type: "run"
      inventory: genie_inventory
      project: git2
      playbook: cs_module/cs_instance_info2.yml
      credentials:
        - "automation_controller_credential"
      state: "present"
      controller_host: "http://{{ genie_ip }}:80"
      controller_username: admin
      controller_password: "{{ admin_password.stdout }}"
        
